doctrine/data-fixtures

- composer.json
- lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php
- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
If you use [EntityManagerDecorator](http://www.doctrine-project.org/api/orm/2.4/class-Doctrine.ORM.Decorator.EntityManagerDecorator.html) or any other entity manager that isn't a Doctrine\ORM\EntityManager class or subclass, then the fixtures break.  Instead, it should use EntityManagerInterface.
> Use EntityManagerInterface instead of EntityManager (to support decorators, etc)

- README.md
- lib/Doctrine/Common/DataFixtures/Loader.php
- tests/Doctrine/Tests/Common/DataFixtures/LoaderTest.php
This PR allows to load fixtures from a single file by adding `loadFromFile` method to `Loader` class.
In some projects which require various fixture sets (e.g. for different setups for various environments) being able to point fixtures only by directory is quite a pain as some fixtures may be reused in few sets. Moving them to subdirectories doesn't solve the problem in some cases as namespaces would have to be adjusted accordingly. There were some issues reported concerning the lack of this feature both in this repo and in DoctrineFixturesBundle. They didn't however contain any code needed to accomplish the goal.
I am planning also to provide a related PR to DoctrineFixturesBundle when this one meets your acceptance.
PHPUnit tests fail in one case, but it does not seem related and it …
> Method for loading fixtures from file added.

- lib/Doctrine/Common/DataFixtures/Loader.php
Fixes #142
Bug introduced in #84
1. The fixture is now registered in the array _before_ recursing.
2. `class_exists` is now called so that the error about unexistant
dependencies is properly thrown in `validateDependencies`.
> Fixed circular dependencies detection

- tests/Doctrine/Tests/Common/DataFixtures/ProxyReferenceRepositoryTest.php
As @stof said:
Getting the reference before the EntityManager is cleared will not
return a proxy instance as the manager already contains a managed
instance.
This test always failed, even where it was first introduced: 5bc3727
Fixes a task in #116
> Fixed test for instanceof Doctrine\ORM\Proxy\Proxy

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- tests/Doctrine/Tests/Common/DataFixtures/Purger/ORMPurgerTest.php
- tests/Doctrine/Tests/Common/DataFixtures/TestEntity/Quoted.php
> Fix Quoting of "joinTable" table names in ORMPurger

- composer.json
- lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php
- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
Fixes #183, #185
Reverts #166, it is causing the BC break, it will be added to `v1.1` instead.
Revert "Use EntityManagerInterface instead of EntityManager (to support decorators, etc)"
Revert "Upgrade doctrine/orm to ~2.4"
This reverts commit 0c96db584a4ccb7cfa4f68d8ee435a3a6f387e81.
This reverts commit 48ec2812ab8d3c044f975b69a0e834c59b0a4a57.
> Revert "Use EntityManagerInterface instead of EntityManager"

- lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php
phpcr-odm only got transactional added in a recent version. we get  https://github.com/symfony-cmf/symfony-cmf/issues/217
the alternative would be to declare a `conflicts` in composer.json to force using a version of phpcr-odm that has transactional.
> handle older versions of phpcr-odm

- lib/Doctrine/Common/DataFixtures/ReferenceRepository.php
Unfortunately `isInIdentityMap` does not exist in Phpcr's DocumentManager which is raising issues when for example we're trying to `setReference` a document.
I'm not an expert in Doctrine stuff so I'm not sure if this is the right way to do it.
Related issue https://github.com/doctrine/phpcr-odm/issues/492
> Use UnitOfWork->contains() instead of isInIdentityMap when Phpcr document

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
Hello. 
Fix for sql error if table name is "order"
````sql                                                                                                                                                               
An exception occurred while executing 'DELETE FROM order':                                                                                                                                                         
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order' at line 1  
```
> fix DELETE sql query

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
`quoteIdentifier` on the table name isn't required, as it it already done by `getTableName` and the `QuoteStrategy` previously.
Infact, this double quoting breaks certain playforms under certain conditions. for example, on postgres with a reserved word table name (`name`), `DELETE FROM ""USER""` is executed, which throws an error.
> quoteIdentifier on table name not required when deleting

- lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php
- tests/Doctrine/Tests/Common/DataFixtures/Sorter/TopologicalSorterTest.php
A first solution to the issue #228. I don't know if this raises further issues.
- fixes #228
> Added support for self referencing classes in the TopologicalSorter

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- tests/Doctrine/Tests/Common/DataFixtures/Purger/ORMPurgerExcludeTest.php
- tests/Doctrine/Tests/Common/DataFixtures/TestPurgeEntity/ExcludedEntity.php
- tests/Doctrine/Tests/Common/DataFixtures/TestPurgeEntity/IncludedEntity.php
Tests for  the  filter schema expression if present in the DBAL connection and checks is the table name has been explicitly excluded.
> Add ability to exclude tables from purge in ORM

- lib/Doctrine/Common/DataFixtures/Loader.php
- tests/Doctrine/Tests/Common/DataFixtures/LoaderTest.php
I'm not sure if this is a good idea, but I've run into the case a few times where you need to get a fixture instance you didn't directly instantiate. Most often this happens when one fixture is automatically added by the loader as a dependency on another fixture.
> Add a getFixture method

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php
- tests/Doctrine/Tests/Common/DataFixtures/Sorter/TopologicalSorterTest.php
Fix #236 issue :
1/ On lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- Node is not erased even if treated in dependencies
- Reverse sort result as previous version
2/ On lib/Doctrine/Common/DataFixtures/Sorter/TopologicalSorter.php
- Exception throwed according to new allowCyclicDependencies attribute
3/ On tests/Doctrine/Tests/Common/DataFixtures/Sorter/TopologicalSorterTest.php
- A new test is written for cyclic dependencies
> Fix sorter issue

- README.md
The class name in the first example is `UserFixtureLoader` which looks good. However the class names in some other examples use a different convention and should not contain a verb.
> Rename example classes names for consistency

- README.md
There is a _Code Block_ with no syntax highlighting and I noted that it was out of the this README's standard.
:)
> Fix syntax highlighting on README

- lib/Doctrine/Common/DataFixtures/Loader.php
Hi guys!
This small patch is needed to support Symfony 4. Specifically, in doctrine/DoctrineFixturesBundle#209, we re-work fixtures to make the classes proper services, which is an easy patch.
However, in this parent class, there are 2 spots where the fixture objects are *instantiated*. That's a problem: the *container* should instantiate them. With this patch, in the bundle, we will be able to throw an exception in `createFixture()` if the object is not already available as a service.
Thanks!
> Symfony 4 support: Hook point to control creating fixtures objects

- tests/Doctrine/Tests/Common/DataFixtures/Sorter/VertexTest.php
Small one: I've refactored a test with [`assertEmpty`](https://phpunit.de/manual/current/pt_br/appendixes.assertions.html#appendixes.assertions.assertEmpty) method.
> Use assertEmpty

- lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php
Implement the access modifier making it PSR-2 compliant.
Just noticed that using some IDE functionality to implement this interface copy/paste the code from it and later marks it as an "error". 
Because doctrine is using PSR-2, i think it makes sense making this one compliant too.
> Added access modifier to DependentFixtureInterface

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- tests/Doctrine/Tests/Common/DataFixtures/Purger/ORMPurgerExcludeTest.php
Fixes #310. This updates the `ORMPurger` class to no longer ignore the `schemaAssetFilter` configuration attribute. This can cause issues when using DoctrineBundle 1.11 and DBAL 2.9 which no longer sets a filter expression but creates a schema asset filter.
> Respect schema asset filters from DBAL 2.9+

- .travis.yml
> Enhancement: Validate composer.json

- lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php
- tests/Doctrine/Tests/Common/DataFixtures/ProxyReferenceRepositoryTest.php
- tests/Doctrine/Tests/Common/DataFixtures/TestEntity/Link.php
- tests/Doctrine/Tests/Common/DataFixtures/TestTypes/UuidType.php
- tests/Doctrine/Tests/Common/DataFixtures/TestValueObjects/Uuid.php
This PR is a fix for #254  
Not sure if I didn't break anything but the tests are passing :smile:
> Fix ID of custom dbal types

- lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php
This makes it easier for PHPStan to understand what's going on.
> Add correct return type to DependentFixtureInterface::getDependencies

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- tests/Doctrine/Tests/Common/DataFixtures/Purger/ORMPurgerTest.php
- tests/Doctrine/Tests/Common/DataFixtures/TestEntity/Group.php
Technically a duplicate of PR #292 but with tests included.
Essentially, purging the database in DELETE mode prior to fixture load fails if any fixture entities use tables names with reserved words (e.g. 'User' in Postgres, or in the test case 'Group' in sqlite). The change makes ORMPurger->getTableName() use the same method as AbstractPlatform::getTruncateTableSQL() uses to get the table name (quoted as necessary).
Test case uses sqlite reserved word 'Group' as an example and checks returned table name is quoted correctly.
Closes #292
> Quote table names that also are reserved keywords

- lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php
- tests/Doctrine/Tests/Common/DataFixtures/Purger/ORMPurgerTest.php
- tests/Doctrine/Tests/Common/DataFixtures/TestEntity/GroupWithSchema.php
PR #334  broke existing code by adding quotes in the middle of table names that used schemas in SQLite - as reported in #338 . 
I've reworked it into a cleaner function that mimics SchemaTool in doctrine/orm. Tests included and pass locally; I've also setup and run a simple test project locally using schema and non-schema entities without issue.
> Fix doctrine/data-fixtures PR#334

- composer.json
- tests/Doctrine/Tests/Common/DataFixtures/Purger/MongoDBPurgerTest.php
See https://github.com/doctrine/data-fixtures/pull/349#issuecomment-683468881.
Suggesting this for a patch release as it involves no code changes and only loosens a require-dev constraint to allow **testing** against ODM 2.0.
> Allow using ODM 2.x

- composer.json
- lib/Doctrine/Common/DataFixtures/ProxyReferenceRepository.php
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues |
- Allows doctrine/common 3.x & doctrine/persistence 2.x
- Bumps 2.x of doctrine/common to 2.13 [because of release notes](https://github.com/doctrine/common/releases/tag/3.0.0)
Thoughts?
> Allows both doctrine/common 3.x & doctrine/persistence 2.x
